// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.DataAccess;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    partial class TasksManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyApi.Models.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Зубы стучат, ноги дрожат, руки крутятся, нервишки мутятся, сегодня я точно его доделаю",
                            EndDate = new DateTime(2024, 2, 3, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Нужно срочно допилить сайт",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Собрать все необходимые данные и подготовить детальный отчет",
                            EndDate = new DateTime(2024, 2, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Подготовить отчет для босса",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Проверить запасы и сделать заказ на нужные офисные материалы",
                            EndDate = new DateTime(2024, 2, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Заказать канцелярские принадлежности",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Создать презентацию и подготовить все необходимые материалы для встречи с клиентом",
                            EndDate = new DateTime(2024, 2, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Подготовить презентацию для клиента",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Зарегистрироваться и успешно завершить курс по новым технологиям до указанной даты",
                            EndDate = new DateTime(2024, 2, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Пройти онлайн-курс по новым технологиям",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Обновить внешний вид блога, добавить новые функции и улучшить пользовательский опыт",
                            EndDate = new DateTime(2024, 2, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Улучшить дизайн личного блога",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Выбрать подходящие тренировки и записаться на них",
                            EndDate = new DateTime(2024, 2, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Записаться на тренировки в фитнес-центре",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Решить место и даты отпуска, подготовить все необходимые документы",
                            EndDate = new DateTime(2024, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Планирование отпуска",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Составить план, выбрать место проведения и организовать корпоративное мероприятие для сотрудников",
                            EndDate = new DateTime(2024, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Организовать корпоративное мероприятие",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Выбрать язык программирования, найти курсы и начать изучение",
                            EndDate = new DateTime(2024, 3, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Изучить новый язык программирования",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "Разработать макет нового приложения, определить основные функциональные требования",
                            EndDate = new DateTime(2024, 2, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Создать прототип нового приложения",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Составить стратегию маркетинга, определить каналы продвижения продукции",
                            EndDate = new DateTime(2024, 2, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Подготовить план маркетинговых мероприятий",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Дописать последние разделы статьи, провести редактирование и опубликовать",
                            EndDate = new DateTime(2024, 2, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Завершить написание статьи для блога",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Подготовить материалы, выбрать платформу для проведения вебинара и провести мероприятие",
                            EndDate = new DateTime(2024, 2, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Организовать вебинар по теме искусственного интеллекта",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            Description = "Подготовить тестовые сценарии, провести тестирование и выявить возможные ошибки",
                            EndDate = new DateTime(2024, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Провести тестирование новой функциональности",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            Description = "Добавить новые проекты, улучшить навигацию и обновить дизайн портфолио",
                            EndDate = new DateTime(2024, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Обновить дизайн личного портфолио",
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            Description = "Обсудить текущие задачи, выявить проблемы и предложить решения",
                            EndDate = new DateTime(2024, 3, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Провести собрание команды",
                            UserId = 7
                        },
                        new
                        {
                            Id = 18,
                            Description = "Зафиксировать ключевые моменты собрания, подготовить протокол и распределить задачи",
                            EndDate = new DateTime(2024, 3, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Подготовить протокол совещания",
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            Description = "Разработать обучающую программу, провести вводное обучение и поддерживать новых членов команды",
                            EndDate = new DateTime(2024, 3, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Провести обучение новых сотрудников",
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            Description = "Анализировать данные маркетинговых показателей, выявлять тенденции и предложить улучшения",
                            EndDate = new DateTime(2024, 3, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Оценить эффективность маркетинговой кампании",
                            UserId = 10
                        },
                        new
                        {
                            Id = 21,
                            Description = "Создать содержательную презентацию и подготовиться к выступлению",
                            EndDate = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Подготовить презентацию для конференции",
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "Определить цели продаж, выбрать стратегии и разработать план выполнения",
                            EndDate = new DateTime(2024, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Разработать стратегию продаж",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            Description = "Проверить уязвимости, оценить уровень безопасности и предложить улучшения",
                            EndDate = new DateTime(2024, 4, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Провести аудит безопасности системы",
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "Составить техническое задание, написать код и провести тестирование",
                            EndDate = new DateTime(2024, 4, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Разработать новую функциональность приложения",
                            UserId = 4
                        },
                        new
                        {
                            Id = 25,
                            Description = "Анализировать текущие процессы, выявлять узкие места и предлагать оптимизации",
                            EndDate = new DateTime(2024, 4, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Оптимизировать процессы в отделе продаж",
                            UserId = 5
                        },
                        new
                        {
                            Id = 26,
                            Description = "Изучить партнеров, определить ключевые моменты и подготовить стратегию переговоров",
                            EndDate = new DateTime(2024, 4, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Подготовиться к переговорам с партнерами",
                            UserId = 6
                        },
                        new
                        {
                            Id = 27,
                            Description = "Создать механизм сбора отзывов, анализировать результаты и внедрить улучшения",
                            EndDate = new DateTime(2024, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Реализовать систему обратной связи для клиентов",
                            UserId = 7
                        },
                        new
                        {
                            Id = 28,
                            Description = "Определить необходимые ресурсы, создать стенд и подготовить презентационные материалы",
                            EndDate = new DateTime(2024, 5, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Подготовиться к выставке в отрасли",
                            UserId = 8
                        },
                        new
                        {
                            Id = 29,
                            Description = "Составить программу поощрений, провести обучение и внедрить систему",
                            EndDate = new DateTime(2024, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Разработать систему мотивации для сотрудников",
                            UserId = 9
                        },
                        new
                        {
                            Id = 30,
                            Description = "Выбрать новый дизайн, обновить контент и оптимизировать пользовательский интерфейс",
                            EndDate = new DateTime(2024, 5, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Обновить дизайн корпоративного сайта",
                            UserId = 10
                        },
                        new
                        {
                            Id = 31,
                            Description = "Подготовить учебные материалы, провести обучение сотрудников и провести тестирование знаний",
                            EndDate = new DateTime(2024, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Провести обучение по новым стандартам безопасности",
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            Description = "Анализировать текущие бизнес-процессы, определить автоматизируемые этапы и внедрить систему",
                            EndDate = new DateTime(2024, 6, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Реализовать систему автоматизации бизнес-процессов",
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            Description = "Создать презентацию, брошюры и другие материалы для представления компании на выставке",
                            EndDate = new DateTime(2024, 6, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Подготовить материалы для участия в выставке",
                            UserId = 3
                        },
                        new
                        {
                            Id = 34,
                            Description = "Анализировать показатели эффективности рекламы, выявлять ключевые успехи и провалы",
                            EndDate = new DateTime(2024, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Оценить эффективность рекламной кампании",
                            UserId = 4
                        },
                        new
                        {
                            Id = 35,
                            Description = "Определить ключевые аспекты успешной командной работы, провести тренинг и укрепить командный дух",
                            EndDate = new DateTime(2024, 6, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Провести тренинг по командной работе",
                            UserId = 5
                        },
                        new
                        {
                            Id = 36,
                            Description = "Разработать стратегию сбора отзывов, определить инструменты и подготовить коммуникационные материалы",
                            EndDate = new DateTime(2024, 6, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Подготовить кампанию по сбору обратной связи от клиентов",
                            UserId = 6
                        },
                        new
                        {
                            Id = 37,
                            Description = "Анализировать текущие логистические схемы, выявлять узкие места и предложить оптимизации",
                            EndDate = new DateTime(2024, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Оптимизировать логистические процессы",
                            UserId = 7
                        },
                        new
                        {
                            Id = 38,
                            Description = "Создать учебный материал, определить ключевые моменты и провести обучение",
                            EndDate = new DateTime(2024, 7, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Разработать обучающий курс для клиентов",
                            UserId = 8
                        },
                        new
                        {
                            Id = 39,
                            Description = "Анализировать реакцию аудитории в социальных сетях, выявлять тренды и рекомендовать улучшения",
                            EndDate = new DateTime(2024, 7, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Оценить эффективность социальных медиа кампании",
                            UserId = 9
                        },
                        new
                        {
                            Id = 40,
                            Description = "Изучить стратегии конкурентов, провести сравнительный анализ и предложить улучшения",
                            EndDate = new DateTime(2024, 7, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Провести анализ конкурентов",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("MyApi.Models.Entities.TaskStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Выполнена"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В процессе"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ожидание"
                        });
                });

            modelBuilder.Entity("MyApi.Models.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "aidar",
                            Pass = "1Exxydnaida"
                        },
                        new
                        {
                            Id = 2,
                            Login = "jane.smith",
                            Pass = "Pass1234"
                        },
                        new
                        {
                            Id = 3,
                            Login = "robert.jones",
                            Pass = "SecurePass"
                        },
                        new
                        {
                            Id = 4,
                            Login = "emily.white",
                            Pass = "StrongPassword"
                        },
                        new
                        {
                            Id = 5,
                            Login = "alex.martin",
                            Pass = "ComplexPass123"
                        },
                        new
                        {
                            Id = 6,
                            Login = "olivia.brown",
                            Pass = "Secure123"
                        },
                        new
                        {
                            Id = 7,
                            Login = "david.miller",
                            Pass = "MyPass567"
                        },
                        new
                        {
                            Id = 8,
                            Login = "emma.wilson",
                            Pass = "SecretPass"
                        },
                        new
                        {
                            Id = 9,
                            Login = "william.jackson",
                            Pass = "Password987"
                        },
                        new
                        {
                            Id = 10,
                            Login = "sophia.davis",
                            Pass = "NewPass123"
                        });
                });

            modelBuilder.Entity("MyApi.Models.Entities.TaskEntity", b =>
                {
                    b.HasOne("MyApi.Models.Entities.TaskStatusEntity", "StatusEntity")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusEntity");

                    b.Navigation("UserEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
